name: uprove
description: U-Prove implementation
authors:
- Sverre <sverre@cs.au.dk>
- Emil 'Skeen' Madsen <sovende@gmail.com>
dependencies:
  unittest: '>=0.10.0'
  bignum: '>=0.0.6 <0.1.0'
  logging: ">=0.9.2 <0.10.0"
executables:
  test: test/runner.dart
